"""Utility modules for SecurePath bot."""

from .discord_helpers import (
    reset_status,
    send_long_message,
    send_long_embed,
    send_structured_analysis_embed,
    format_percentage,
    format_price,
    format_large_number,
    create_progress_embed,
    is_admin_user,
    get_user_display_name,
    truncate_text,
    extract_command_args,
)

from .validators import (
    validate_discord_id,
    validate_url,
    validate_image_url,
    validate_query_length,
    validate_command_name,
    validate_username,
    sanitize_filename,
    validate_model_name,
    validate_cost,
    validate_token_count,
    extract_mentions,
    extract_channel_mentions,
    is_spam_like,
)

from .formatting import (
    format_currency,
    format_percentage as format_percentage_detailed,
    format_large_number as format_large_number_detailed,
    format_duration,
    format_timestamp,
    clean_text_for_discord,
    escape_markdown,
    format_code_block,
    format_inline_code,
    format_usage_stats,
    format_model_name,
    format_error_message,
    format_list_items,
    format_embed_field_value,
    truncate_with_ellipsis,
)

__all__ = [
    # Discord helpers
    'reset_status',
    'send_long_message',
    'send_long_embed', 
    'send_structured_analysis_embed',
    'create_progress_embed',
    'is_admin_user',
    'get_user_display_name',
    'truncate_text',
    'extract_command_args',
    
    # Validators
    'validate_discord_id',
    'validate_url',
    'validate_image_url',
    'validate_query_length',
    'validate_command_name',
    'validate_username',
    'sanitize_filename',
    'validate_model_name',
    'validate_cost',
    'validate_token_count',
    'extract_mentions',
    'extract_channel_mentions',
    'is_spam_like',
    
    # Formatting
    'format_currency',
    'format_percentage',
    'format_percentage_detailed',
    'format_price',
    'format_large_number',
    'format_large_number_detailed',
    'format_duration',
    'format_timestamp',
    'clean_text_for_discord',
    'escape_markdown',
    'format_code_block',
    'format_inline_code',
    'format_usage_stats',
    'format_model_name',
    'format_error_message',
    'format_list_items',
    'format_embed_field_value',
    'truncate_with_ellipsis',
]